apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: app-env-secret
  literals:
  - QR_CODE_GATEWAY_ROOT_URL=https://api.mercadopago.com/instore/orders/qr/seller/collectors/1870524610/pos/SUC003POS002/qrs
  - QR_CODE_GATEWAY_TOKEN=Bearer APP_USR-6055163631945828-062216-33971ff71b8cbeeeebff22bdfb6b36cc-1870524610
  - WEBHOOK_MERCADO_LIVRE_PAYMENT=http://a1f99c28366a04f8b8378a25e41f7e6e-1899370698.us-east-1.elb.amazonaws.com/api/webhook/ml/payment
  - POSTGRES_PASSWORD=FastFoodDatabasePassword
  - MONGO_PASSWORD=g5QKhgkKvu2oX3nK