apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-customer
data:
  POSTGRES_USER: fastfood_db_user
  POSTGRES_DB: fastfood_db_customer
  DB_HOST: fastfood-database.cfaoo0ogib3a.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  AWS_COGNITO_USER_POOL_ID: us-east-1_79AHMQBdx
  AWS_COGNITO_CLIENT_ID: 1mja3mq2unc2j27vek76u4r4dp
  AWS_COGNITO_GROUP_USER: group-users
  AWS_COGNITO_GROUP_ADMIN: group-admin
  AWS_REGION: us-east-1