apiVersion: v1
kind: Service
metadata:
  name: svc-orders
  labels:
    kubernetes.io/service-name: svc-orders
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4210
  selector:
    app: fastfood-orders

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-orders
  labels:
    app: fastfood-orders
spec:
  selector:
    matchLabels:
      app: fastfood-orders
  template:
    metadata:
      labels:
        app: fastfood-orders
    spec:
      containers:
      - name: fastfood-orders
        image: thiagoluis88/fastfood-orders:1.0.1
        envFrom:
          - secretRef:
              name: app-env-secret
          - configMapRef:
              name: cm-orders
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password
                key: POSTGRES_PASSWORD
          - name: QR_CODE_GATEWAY_ROOT_URL
            valueFrom:
              secretKeyRef:
                name: qr-code-gateway-root-url
                key: QR_CODE_GATEWAY_ROOT_URL
          - name: QR_CODE_GATEWAY_TOKEN
            valueFrom:
              secretKeyRef:
                name: qr-code-gateway-token
                key: QR_CODE_GATEWAY_TOKEN
          - name: WEBHOOK_MERCADO_LIVRE_PAYMENT
            valueFrom:
              secretKeyRef:
                name: webhool-mercado-livre-payment
                key: WEBHOOK_MERCADO_LIVRE_PAYMENT
        ports:
        - containerPort: 4210
          # name: app
        # - containerPort: 3211
        #   name: redoc
        livenessProbe:
          httpGet:
            path: /health
            port: 4210
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 4210
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          initialDelaySeconds: 3
        resources:
          requests:
            cpu: 50m
      # volumes:
      #   - name: secrets-store-inline
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "aws-secrets"
