apiVersion: v1
kind: Service
metadata:
  name: svc.orders
  labels:
    kubernetes.io/service-name: svc.orders
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4210
  selector:
    app: fastfood-orders

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-orders
  labels:
    app: fastfood-orders
spec:
  selector:
    matchLabels:
      app: fastfood-orders
  template:
    metadata:
      labels:
        app: fastfood-orders
    spec:
      containers:
      - name: fastfood-orders
        image: thiagoluis88/fastfood-orders:0.0.38
        envFrom:
          - secretRef:
              name: app-env-secret
          - configMapRef:
              name: cm-orders
        ports:
        - containerPort: 4210
          # name: app
        # - containerPort: 3211
        #   name: redoc
        livenessProbe:
          httpGet:
            path: /health
            port: 4210
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 4210
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          initialDelaySeconds: 3
        resources:
          requests:
            cpu: 50m
