apiVersion: v1
kind: Service
metadata:
  name: svc.payment
  labels:
    kubernetes.io/service-name: svc.payment
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5210
  selector:
    app: fastfood-payment

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-payment
  labels:
    app: fastfood-payment
spec:
  selector:
    matchLabels:
      app: fastfood-payment
  template:
    metadata:
      labels:
        app: fastfood-payment
    spec:
      containers:
      - name: fastfood-payment
        image: thiagoluis88/fastfood-payment:1.0.0
        envFrom:
          - configMapRef:
              name: cm-payment
        ports:
        - containerPort: 5210
          # name: app
        # - containerPort: 3211
        #   name: redoc
        livenessProbe:
          httpGet:
            path: /health
            port: 5210
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 5210
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          initialDelaySeconds: 3
        resources:
          requests:
            cpu: 50m
