apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-fastfood-customer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastfood-customer
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-fastfood-orders
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastfood-orders
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-fastfood-payment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastfood-payment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
