apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "postgres-password"
        objectType: "ssmparameter"
      - objectName: "mong-password"
        objectType: "ssmparameter"
      - objectName: "qr-code-gateway-root-url"
        objectType: "ssmparameter"
      - objectName: "qr-code-gateway-token"
        objectType: "ssmparameter"
      - objectName: "webhool-mercado-livre-payment"
        objectType: "ssmparameter"