apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: service-fastfood-database
  labels:
    app: service-fastfood-database
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5432
      nodePort: 31002
  selector:
    app: database

---

apiVersion: v1
kind: Service
metadata:
  name: service-database-internal
spec:
  selector:
    app: database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-fastfood-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: fastfood-database
          image: 'postgres:16-alpine'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: app-env-secret
            - configMapRef:
                name: cm-app
            - configMapRef:
                name: cm-database
          volumeMounts:
            - name: postgresdata 
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim