# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy Fastfood in EKS

on:
  workflow_dispatch: 

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.FASTFOOD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.FASTFOOD_AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.FASTFOOD_AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update kube config
        run: aws eks update-kubeconfig --region us-east-1 --name fastfood-cluster
    
      - name: Deploy to EKS
        run: |
          kubectl apply -k infra/k8s/secret/
          kubectl apply -f infra/k8s/configmaps/
          kubectl apply -f infra/k8s/metrics/
          kubectl apply -f infra/k8s/hpa/
          kubectl apply -f infra/k8s/deployments/


